# SwiftLint Configuration for Little Moon

# Paths to include/exclude
included:
  - Little Moon

excluded:
  - Pods
  - build
  - .build

# Enabled/Disabled Rules
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing

# Rule Configurations
identifier_name:
  min_length: 2
  max_length: 60

type_name:
  min_length: 3
  max_length: 60
  validates_start_with_lowercase: false
  allowed_symbols: ["_"]

function_body_length:
  warning: 100
  error: 200

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

# Reporting
reporter: "xcode"
